In [33]:
import numpy as np

### 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’


In [56]:
def foo_1(arr, target):
    if target not in arr:
        return 'no item found'

    differences = np.abs(arr-target)

    closest = np.where(differences == np.min(differences))[0]

    return closest

arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 7
print(foo_1(arr, target))

[2 3 4 5 6 8]


In [41]:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 11
print(foo_1(arr, target))

no item found


### 2. Write a user defined function foo_2 that takes a 1 or 2 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.

In [48]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis)

    return non_zero

arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

result = foo_2(arr, axis=1)
print(result)

[4 1 2]


In [46]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis)

    return non_zero

arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

result = foo_2(arr, axis=0)
print(result)

[2 2 2 1]


In [114]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis=axis)

    return non_zero

arr1 = np.array([[[1, 2, 3, 4],
                  [0, 5, 0, 0],
                  [2, 0, 1, 0]],

                 [[2, 0, 1, 0],
                  [0, 5, 0, 0],
                  [1, 2, 3, 4]]])

result = foo_2(arr1, axis=0)
print(result)

[[2 1 2 1]
 [0 2 0 0]
 [2 1 2 1]]


In [115]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis=axis)

    return non_zero

arr1 = np.array([[[1, 2, 3, 4],
                  [0, 5, 0, 0],
                  [2, 0, 1, 0]],

                 [[2, 0, 1, 0],
                  [0, 5, 0, 0],
                  [1, 2, 3, 4]]])

result = foo_2(arr1, axis=1)
print(result)

[[2 2 2 1]
 [2 2 2 1]]


In [116]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis=axis)

    return non_zero

arr1 = np.array([[[1, 2, 3, 4],
                  [0, 5, 0, 0],
                  [2, 0, 1, 0]],

                 [[2, 0, 1, 0],
                  [0, 5, 0, 0],
                  [1, 2, 3, 4]]])

result = foo_2(arr1, axis=2)
print(result)

[[4 1 2]
 [2 1 4]]


### 3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [122]:
student_scores = np.random.randint(60,100,(4,3))
print(student_scores)

above_90_mask = np.any(student_scores > 90, axis=1)
resulting_array = student_scores[above_90_mask]

print('Resulting Array: ')
print(resulting_array)

[[91 94 80]
 [85 93 66]
 [67 80 73]
 [96 83 70]]
Resulting Array: 
[[91 94 80]
 [85 93 66]
 [96 83 70]]


### 3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

In [76]:
sales_data = np.random.randint(90,350,(4,4))
print(sales_data)

mean_values = np.mean(sales_data, axis=1)

median_values = np.median(sales_data, axis=1)

standard_deviation_values = np.std(sales_data, axis=1)

best_month_sales = np.argmax(sales_data, axis=1)

for i in range(len(mean_values)):
    print(f"Product {i+1}:")
    print(f"Mean: {mean_values[i]}")
    print(f"Median: {median_values[i]}")
    print(f"Standard Deviation: {standard_deviation_values[i]}")
    print(f"Month with the highest sales: Month {best_month_sales[i] + 1}")
    print()

[[199 342 261 251]
 [ 94 242 171 158]
 [303 292 234 184]
 [346 299 165 328]]
Product 1:
Mean: 263.25
Median: 256.0
Standard Deviation: 51.197534120307004
Month with the highest sales: Month 2

Product 2:
Mean: 166.25
Median: 164.5
Standard Deviation: 52.55651719815536
Month with the highest sales: Month 2

Product 3:
Mean: 253.25
Median: 263.0
Standard Deviation: 47.80886424084973
Month with the highest sales: Month 1

Product 4:
Mean: 284.5
Median: 313.5
Standard Deviation: 71.00176054155277
Month with the highest sales: Month 1



### 3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.


In [140]:
random_array = np.random.randint(1, 101, size=1000)
print(random_array)

unique_values, counts = np.unique(random_array, return_counts=1)

sorted_indices = np.argsort(counts)[::-1]

top_values = unique_values[sorted_indices[:10]]
top_counts = counts[sorted_indices[:10]]

print("Top 10 most frequently occurring values:")
for value, count in zip(top_values, top_counts):
    print(f"{value}: {count} occurrences")

[ 94  23  93  91  75   1  46  18  35  15  74  14  31  11  33  12  40  98
  96  86  57  70  94  19  91  28  33   8  72  91  87 100  19  28  31  80
  90   5  69  44  79  94  98  39  90  86  80  85  30  65  95  83  51  33
  71  94  70   4  53  87  60  79  41  59  48  67  91  59  98  29  92   4
  41  42  26  61  36  61  18  45  57  32  86  94  63  91  71  11  52  55
  45  12  49  30  90  47   6  49  43  43  60  96  28  66  65  91   9  24
  49  16  28  47   3  49  83  76  82  69  74  69   6  12  63  75  84  75
  77  80  13  55  25  59  30  63  44  66  31  81   8  54  94   5  24  35
  67  67  54  81  82  88  85  41  42  30  27  74  68  98  24  85  28  12
  77  44  52  17  54  84  34  52  51  70  95  99  40  92  24   5  95  78
   3  81  46  87  84  61   3  25  32   4  55  94  31  82  77  60  53  36
   1  95  66  74  66   8  72  29  48   7  95  35  84  84  78   9  40  96
  24  85  96  19   8  15  36  77  50  24  63  30  87  83  66  55  54  18
  70   8  20  21  69  66  48  53   3  77  52   7   